name: CI

on:
  push:
    branches: [ main, master ]   # змініть, якщо у вас інша гілка за замовчуванням
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test
        run: mvn -q -DskipTests=false test

      - name: Package (fat jar)
        run: mvn -q -DskipTests package

      - name: Upload fat jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: word-search-fat-jar
          path: target/*-jar-with-dependencies.jar
